version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
      - elasticsearch
      - redis
    environment:
      - NODE_ENV=production
    restart: always
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: productdb
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    restart: always
  redis:
    image: redis:6
    restart: always

volumes:
  postgres_data:
  elasticsearch_data:
